// EngineSnap — one PlayerObject's physics state, exactly as the real engine holds it.
//
// Part of the engine-decoding program (plan: "Programme de déchiffrage du gameplay GD").
// The lockstep bench validates ONE ported engine function at a time: load the real state
// captured just before a call, run our port of that function, compare with the real state
// captured just after — so there is no trajectory, no drift, and no chance for two bugs to
// cancel. This struct is that state.
//
// The field list is NOT hand-written. It is src/sim/engine/SnapFields.inc, generated by
// tools/gen_snapfields.py from the engine's own code: every PlayerObject member read or
// written by the in-scope engine functions, with its compiler-exact offset
// (tools/gen_offsets.py). The mod's capture hook expands the SAME list, so what is captured
// and what is compared can never drift apart.
//
// Geode-free on purpose (gdsim is standalone): engine types are mapped to plain ones —
//   CCPoint -> two floats (name_x, name_y), GameObject* -> identity (m_uniqueID, 0 = null),
//   SeedValueRSV -> the decoded int.
#pragma once
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace gdsim::engine {

// gen_snapfields.py writes multi-word types with underscores so they survive the macro.
using unsigned_char = unsigned char;
using unsigned_int  = unsigned int;

struct EngineSnap {
#define SNAP_SCALAR(T, n, off) T n{};
#define SNAP_POINT(n, off)     float n##_x{}, n##_y{};
#define SNAP_OBJ(n, off)       int32_t n{};
#define SNAP_SEED(n, off)      int32_t n{};
#include "SnapFields.inc"
#undef SNAP_SCALAR
#undef SNAP_POINT
#undef SNAP_OBJ
#undef SNAP_SEED
};

// Visit every field as (name, value-as-double) — for diffing and for readable dumps.
// Doubles hold every captured type exactly (float, int32, bool all fit losslessly).
template <class F>
inline void forEachField(const EngineSnap& s, F&& f) {
#define SNAP_SCALAR(T, n, off) f(#n, (double)s.n);
#define SNAP_POINT(n, off)     f(#n "_x", (double)s.n##_x); f(#n "_y", (double)s.n##_y);
#define SNAP_OBJ(n, off)       f(#n, (double)s.n);
#define SNAP_SEED(n, off)      f(#n, (double)s.n);
#include "SnapFields.inc"
#undef SNAP_SCALAR
#undef SNAP_POINT
#undef SNAP_OBJ
#undef SNAP_SEED
}

// Every field that differs between the real engine's state and ours, in list order.
struct FieldDiff { std::string field; double expected, got; };
inline std::vector<FieldDiff> diff(const EngineSnap& real, const EngineSnap& ours) {
    std::vector<double> a, b;
    std::vector<std::string> names;
    forEachField(real, [&](const char* n, double v) { names.emplace_back(n); a.push_back(v); });
    forEachField(ours, [&](const char*, double v) { b.push_back(v); });
    std::vector<FieldDiff> out;
    for (size_t i = 0; i < a.size(); ++i)
        // Exact comparison, on purpose: the engine quantises velocities to 3 decimals and
        // every other field is a flag, a count or a float copied verbatim. A tolerance
        // would silently absorb exactly the kind of error this bench exists to expose.
        if (!(a[i] == b[i]) && !(a[i] != a[i] && b[i] != b[i]))   // NaN == NaN counts as equal
            out.push_back({names[i], a[i], b[i]});
    return out;
}

// Binary layout: the fields in list order, each in its native width. Both sides are
// compiled from the same SnapFields.inc, so the layout matches by construction; the
// header carries a checksum of the field list to catch a stale capture instead.
inline uint32_t layoutHash() {
    uint32_t h = 2166136261u;                                      // FNV-1a
    auto mix = [&](const char* s) { for (; *s; ++s) { h ^= (uint8_t)*s; h *= 16777619u; } };
#define SNAP_SCALAR(T, n, off) mix(#T); mix(#n);
#define SNAP_POINT(n, off)     mix("pt"); mix(#n);
#define SNAP_OBJ(n, off)       mix("obj"); mix(#n);
#define SNAP_SEED(n, off)      mix("seed"); mix(#n);
#include "SnapFields.inc"
#undef SNAP_SCALAR
#undef SNAP_POINT
#undef SNAP_OBJ
#undef SNAP_SEED
    return h;
}

inline void write(std::FILE* f, const EngineSnap& s) {
#define SNAP_SCALAR(T, n, off) std::fwrite(&s.n, sizeof(s.n), 1, f);
#define SNAP_POINT(n, off)     std::fwrite(&s.n##_x, 4, 1, f); std::fwrite(&s.n##_y, 4, 1, f);
#define SNAP_OBJ(n, off)       std::fwrite(&s.n, 4, 1, f);
#define SNAP_SEED(n, off)      std::fwrite(&s.n, 4, 1, f);
#include "SnapFields.inc"
#undef SNAP_SCALAR
#undef SNAP_POINT
#undef SNAP_OBJ
#undef SNAP_SEED
}

inline bool read(std::FILE* f, EngineSnap& s) {
    bool ok = true;
#define SNAP_SCALAR(T, n, off) ok = ok && std::fread(&s.n, sizeof(s.n), 1, f) == 1;
#define SNAP_POINT(n, off)     ok = ok && std::fread(&s.n##_x, 4, 1, f) == 1 && std::fread(&s.n##_y, 4, 1, f) == 1;
#define SNAP_OBJ(n, off)       ok = ok && std::fread(&s.n, 4, 1, f) == 1;
#define SNAP_SEED(n, off)      ok = ok && std::fread(&s.n, 4, 1, f) == 1;
#include "SnapFields.inc"
#undef SNAP_SCALAR
#undef SNAP_POINT
#undef SNAP_OBJ
#undef SNAP_SEED
    return ok;
}

} // namespace gdsim::engine
