"""gen_offsets.py — compiler-exact field offsets for any GD class, reproducibly.

WHY: the engine functions we port read PlayerObject / GJBaseGameLayer fields by raw byte
offset (`param_1 + 0x9b9`). Only offsets produced by MSVC itself are trustworthy — struct
layout is ABI-dependent and GD is MSVC-built. `bromamap.py fields` computes offsets from
declaration order and is NOT reliable; it is only a list of names. Until now the trustworthy
set was 70 hand-harvested entries in gd_fields.txt. This script harvests ALL of them.

HOW (the documented MSVC trick, automated):
    template<size_t N> struct OFFSET_IS;                     // declared, never defined
    static OFFSET_IS<offsetof(PlayerObject, m_x)> probe_0;   // -> error C2079 ... OFFSET_IS<N>
Each probe is a compile error whose message contains the exact offset. The probes go into
a dedicated src/zz_offset_probe.cpp (CMakeLists globs src/*.cpp with CONFIGURE_DEPENDS, so a
new file is picked up, and removing it drops it again) — no existing source is touched.
MSVC aborts after 100 errors (fatal C1003), so members are probed in batches.

USAGE (from the repo root, GD closed is NOT required — nothing is installed):
    py -3 tools/gen_offsets.py PlayerObject
    py -3 tools/gen_offsets.py GJBaseGameLayer
Results are merged into tools/gd_fields.txt: every existing line for OTHER classes is kept,
this class's lines are replaced by the fresh harvest. The build is left clean afterwards.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BINDING_DIR = os.path.join(ROOT, "build", "bindings", "bindings", "Geode", "binding")
PROBE = os.path.join(ROOT, "src", "zz_offset_probe.cpp")
FIELDS = os.path.join(ROOT, "tools", "gd_fields.txt")
BATCH = 90  # MSVC stops at 100 errors (C1003)

MEMBER_RE = re.compile(r"^\s*(?!return\b)(?!using\b)(?!typedef\b)[A-Za-z_][\w:<>,\s\*&]*?[\s\*&]"
                       r"(?P<name>[A-Za-z_]\w*)\s*;\s*$")


def class_members(cls):
    """Every data member declared directly in `cls` (base-class members are not included:
    offsetof of a base member through the derived type is legal but those belong to the
    base's own harvest). Members of anonymous unions are included."""
    path = os.path.join(BINDING_DIR, cls + ".hpp")
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()
    # The data members are the plain `Type name;` lines at class scope. Methods always
    # carry '(' and doc comments start with '*' or '/', so a line-based filter is enough.
    names = []
    for ln in lines:
        s = ln.strip()
        if not s.endswith(";") or "(" in s or s.startswith(("/", "*", "#", "}", "friend")):
            continue
        m = MEMBER_RE.match(ln)
        if m:
            names.append(m.group("name"))
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def probe_batch(cls, members):
    body = ["// GENERATED by tools/gen_offsets.py — deleted automatically. Do not commit.",
            "#include <Geode/Geode.hpp>",
            "#include <cstddef>",
            "using namespace geode::prelude;",
            "template <size_t N> struct OFFSET_IS;"]
    for i, m in enumerate(members):
        body.append("static OFFSET_IS<offsetof(%s, %s)> probe_%d;" % (cls, m, i))
    with open(PROBE, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body) + "\n")
    r = subprocess.run(["cmake", "--build", "build", "--config", "RelWithDebInfo",
                        "--target", "Pathfinder"],
                       cwd=ROOT, capture_output=True, text=True, errors="replace")
    out = r.stdout + r.stderr
    found = {}
    for m in re.finditer(r"'probe_(\d+)'[^\n]*?OFFSET_IS<\s*(0x[0-9a-fA-F]+|\d+)\s*>", out):
        idx, val = int(m.group(1)), m.group(2)
        found[idx] = int(val, 16) if val.lower().startswith("0x") else int(val)
    return found, out


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    cls = sys.argv[1]
    members = class_members(cls)
    print("%s: %d members to probe" % (cls, len(members)))
    results, missing = {}, []
    try:
        for start in range(0, len(members), BATCH):
            chunk = members[start:start + BATCH]
            found, out = probe_batch(cls, chunk)
            if not found:
                # The FIRST build after the probe file appears is spent on CMake noticing it
                # (CONFIGURE_DEPENDS re-glob + regenerate) and can finish without compiling the
                # probe at all — observed: batch 0 resolved 0/90 while every later batch was
                # 90/90. One retry is enough; a real compile error would fail again.
                found, out = probe_batch(cls, chunk)
            for i, name in enumerate(chunk):
                if i in found:
                    results[name] = found[i]
                else:
                    missing.append(name)
            print("  batch %d-%d: %d/%d resolved" % (start, start + len(chunk) - 1,
                                                    len(found), len(chunk)))
            if not found:
                # Nothing parsed at all: most likely the probe file itself failed to compile
                # for another reason. Show the first error lines instead of guessing.
                errs = [l for l in out.splitlines() if "error" in l.lower()][:8]
                print("  !! no probe errors parsed; first errors:\n    " + "\n    ".join(errs))
    finally:
        if os.path.exists(PROBE):
            os.remove(PROBE)
        # Deleting the file is not enough: the generated .vcxproj still lists it until CMake
        # re-globs, and the next `cmake --build` then fails with C1083 "cannot open source
        # file zz_offset_probe.cpp" (observed). Reconfigure so the build is left clean.
        subprocess.run(["cmake", "build"], cwd=ROOT, capture_output=True, text=True)

    # Merge into gd_fields.txt: keep other classes, replace this one.
    keep = []
    if os.path.exists(FIELDS):
        with open(FIELDS, encoding="utf-8-sig") as fh:
            keep = [l.rstrip("\n") for l in fh if l.strip() and not l.startswith(cls + "\t")]
    fresh = ["%s\t0x%x\t%s" % (cls, off, name) for name, off in results.items()]
    merged = sorted(keep + fresh, key=lambda l: (l.split("\t")[0], int(l.split("\t")[1], 16)))
    with open(FIELDS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(merged) + "\n")

    print("%s: %d offsets written, %d unresolved" % (cls, len(results), len(missing)))
    if missing:
        print("  unresolved: " + ", ".join(missing[:30]) + (" ..." if len(missing) > 30 else ""))
    return 0 if not missing else 1


if __name__ == "__main__":
    sys.exit(main())
